version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - dependencies
    groups:
      github-actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - python
    cooldown:
      default-days: 7
    versioning-strategy: lockfile-only
